django-1  | foo ... foo done
django-1  | aaron ... aaron done
django-1  | ana ... ana done
django-1  | + exec /api-bot/.venv/bin/python /api-bot/apibot.py
django-1  | + exec /api-bot/.venv/bin/python /api-bot/apibot.py
django-1  | + cd /bridge/project
django-1  | + export PGHOST=postgres
django-1  | + PGHOST=postgres
django-1  | + exec poetry run daphne --verbosity 3 --bind 0.0.0.0 --port 9000 project.asgi:application '--log-fmt=%(asctime)sZ %(levelname)s %(name)s %(filename)s %(funcName)s %(message)s'
django-1  | + exec /api-bot/.venv/bin/python /api-bot/apibot.py
django-1  | 2025-01-27T19:14:24+0000 DEBUG apibot (    27) ?         : apibot.py 65 get_http_session Fetching http://localhost:9000/three-way-login/ ...
django-1  | 2025-01-27T19:14:24+0000 DEBUG apibot (    28) ?         : apibot.py 65 get_http_session Fetching http://localhost:9000/three-way-login/ ...
django-1  | 2025-01-27T19:14:24+0000 DEBUG apibot (    30) ?         : apibot.py 65 get_http_session Fetching http://localhost:9000/three-way-login/ ...
django-1  | 2025-01-27T19:14:24+0000 INFO  apibot (    30) ?         : apibot.py 69 get_http_session Got HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /three-way-login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x783c7f00acf0>: Failed to establish a new connection: [Errno 111] Connection refused')); probably the server isn't yet up, so we'll just calmly exit
django-1  | 2025-01-27T19:14:24+0000 INFO  apibot (    27) ?         : apibot.py 69 get_http_session Got HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /three-way-login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x780276f8a900>: Failed to establish a new connection: [Errno 111] Connection refused')); probably the server isn't yet up, so we'll just calmly exit
django-1  | 2025-01-27T19:14:24+0000 INFO  apibot (    28) ?         : apibot.py 69 get_http_session Got HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /three-way-login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x730d3882acf0>: Failed to establish a new connection: [Errno 111] Connection refused')); probably the server isn't yet up, so we'll just calmly exit
django-1  | os.environ["DJANGO_SETTINGS_MODULE"]='project.prod_settings'
django-1  | settings.DEPLOYMENT_ENVIRONMENT='production' settings.SECURE_SSL_REDIRECT=False
django-1  | settings.VERSION='6e2c5ee 2025-01-27'
django-1  | settings.GIT_SYMBOLIC_REF='refs/heads/main'
django-1  | + exec /api-bot/.venv/bin/python /api-bot/apibot.py
django-1  | + exec /api-bot/.venv/bin/python /api-bot/apibot.py
django-1  | + exec /api-bot/.venv/bin/python /api-bot/apibot.py
django-1  | 2025-01-27T19:14:26+0000 DEBUG apibot (    36) ?         : apibot.py 65 get_http_session Fetching http://localhost:9000/three-way-login/ ...
django-1  | 2025-01-27T19:14:26+0000 INFO  apibot (    36) ?         : apibot.py 69 get_http_session Got HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /three-way-login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7027b9c09a90>: Failed to establish a new connection: [Errno 111] Connection refused')); probably the server isn't yet up, so we'll just calmly exit
django-1  | 2025-01-27T19:14:26+0000 DEBUG apibot (    35) ?         : apibot.py 65 get_http_session Fetching http://localhost:9000/three-way-login/ ...
django-1  | 2025-01-27T19:14:26+0000 DEBUG apibot (    37) ?         : apibot.py 65 get_http_session Fetching http://localhost:9000/three-way-login/ ...
django-1  | 2025-01-27T19:14:26+0000 INFO  apibot (    35) ?         : apibot.py 69 get_http_session Got HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /three-way-login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7b5b0998da90>: Failed to establish a new connection: [Errno 111] Connection refused')); probably the server isn't yet up, so we'll just calmly exit
django-1  | 2025-01-27T19:14:26+0000 INFO  apibot (    37) ?         : apibot.py 69 get_http_session Got HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /three-way-login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x738c60e29a90>: Failed to establish a new connection: [Errno 111] Connection refused')); probably the server isn't yet up, so we'll just calmly exit
django-1  | + exec /api-bot/.venv/bin/python /api-bot/apibot.py
django-1  | + exec /api-bot/.venv/bin/python /api-bot/apibot.py
django-1  | + exec /api-bot/.venv/bin/python /api-bot/apibot.py
django-1  | 2025-01-27T19:14:28+0000 DEBUG apibot (    44) ?         : apibot.py 65 get_http_session Fetching http://localhost:9000/three-way-login/ ...
django-1  | 2025-01-27T19:14:28+0000 DEBUG apibot (    42) ?         : apibot.py 65 get_http_session Fetching http://localhost:9000/three-way-login/ ...
django-1  | 2025-01-27T19:14:28+0000 DEBUG apibot (    43) ?         : apibot.py 65 get_http_session Fetching http://localhost:9000/three-way-login/ ...
django-1  | 2025-01-27T19:14:28+0000 DEBUG apibot (    44) ?         : apibot.py 201 <module> player_blob is {'player-name': 'aaron', 'player_pk': 38, 'comment': 'Oh look, aaron used the skeleton key', 'table_pk': 18, 'hand_pk': 316}
django-1  | 2025-01-27T19:14:28+0000 DEBUG apibot (    44) aaron     : apibot.py 206 <module> Oh look, my name isn't really 38; it's aaron
django-1  | 2025-01-27T19:14:28+0000 DEBUG apibot (    42) ?         : apibot.py 201 <module> player_blob is {'player-name': 'ana', 'player_pk': 32, 'comment': 'Oh look, ana used the skeleton key', 'table_pk': 18, 'hand_pk': 316}
django-1  | 2025-01-27T19:14:28+0000 DEBUG apibot (    42) ana       : apibot.py 206 <module> Oh look, my name isn't really 32; it's ana
django-1  | 2025-01-27T19:14:28+0000 DEBUG apibot (    43) ?         : apibot.py 201 <module> player_blob is {'player-name': 'foo', 'player_pk': 44, 'comment': 'Oh look, foo used the skeleton key', 'table_pk': 18, 'hand_pk': 316}
django-1  | 2025-01-27T19:14:28+0000 DEBUG apibot (    43) foo       : apibot.py 206 <module> Oh look, my name isn't really 44; it's foo
django-1  | 2025-01-27T19:14:28+0000 DEBUG apibot (    44) aaron     : apibot.py 105 get_xscript Got transcript from http://localhost:9000/serialized/hand/316/: HandTranscript, 12 calls, 52 plays, self.seat_cycle[0].name='South'
django-1  | 2025-01-27T19:14:28+0000 DEBUG apibot (    44) aaron     : apibot.py 119 _is_it_my_turn Hand is over.
django-1  | 2025-01-27T19:14:28+0000 DEBUG apibot (    44) aaron     : apibot.py 164 _maybe_post It's not my turn
django-1  | 2025-01-27T19:14:28+0000 INFO  apibot (    44) aaron     : apibot.py 223 <module> About to start event-fetching loop from http://localhost:9000/events/player/system:player:38/, last_id system%3Aplayer%3A38:878
django-1  | 2025-01-27T19:14:28+0000 DEBUG apibot (    42) ana       : apibot.py 105 get_xscript Got transcript from http://localhost:9000/serialized/hand/316/: HandTranscript, 12 calls, 52 plays, self.seat_cycle[0].name='South'
django-1  | 2025-01-27T19:14:28+0000 DEBUG apibot (    42) ana       : apibot.py 119 _is_it_my_turn Hand is over.
django-1  | 2025-01-27T19:14:28+0000 DEBUG apibot (    42) ana       : apibot.py 164 _maybe_post It's not my turn
django-1  | 2025-01-27T19:14:28+0000 INFO  apibot (    42) ana       : apibot.py 223 <module> About to start event-fetching loop from http://localhost:9000/events/player/system:player:32/, last_id system%3Aplayer%3A32:877
django-1  | 2025-01-27T19:14:28+0000 DEBUG apibot (    43) foo       : apibot.py 105 get_xscript Got transcript from http://localhost:9000/serialized/hand/316/: HandTranscript, 12 calls, 52 plays, self.seat_cycle[0].name='South'
django-1  | 2025-01-27T19:14:28+0000 DEBUG apibot (    43) foo       : apibot.py 119 _is_it_my_turn Hand is over.
django-1  | 2025-01-27T19:14:28+0000 DEBUG apibot (    43) foo       : apibot.py 164 _maybe_post It's not my turn
django-1  | 2025-01-27T19:14:28+0000 INFO  apibot (    43) foo       : apibot.py 223 <module> About to start event-fetching loop from http://localhost:9000/events/player/system:player:44/, last_id system%3Aplayer%3A44:134
