Django version 5.1, using settings 'project.settings'
Starting ASGI/Daphne version 4.1.2 development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
HTTP GET /player/6/ 200 [0.14, 192.168.4.90:60324]
HTTP GET /static/django_eventstream/reconnecting-eventsource.js 304 [0.00, 192.168.4.90:60332]
HTTP GET /static/django_eventstream/eventsource.min.js 304 [0.00, 192.168.4.90:60328]
HTTP GET /events/player/players:6_15 301 [0.01, 192.168.4.90:60328]
HTTP POST /send_player_message/6 200 [0.05, 192.168.4.90:49260]
HTTP GET /player/15/ 200 [0.13, 127.0.0.1:64167]
HTTP GET /events/player/players:6_15 301 [0.01, 127.0.0.1:64169]
HTTP GET /player/6/ 200 [0.05, 127.0.0.1:64171]
HTTP GET /events/player/players:5_6 301 [0.01, 127.0.0.1:64173]
HTTP GET /player/6/ 200 [0.06, 127.0.0.1:64175]
HTTP GET /events/player/players:5_6 301 [0.03, 127.0.0.1:64177]
HTTP GET /player/6/ 200 [0.06, 127.0.0.1:64181]
HTTP GET /events/player/players:6_6 301 [0.02, 127.0.0.1:64183]
HTTP GET /player/5/ 200 [0.05, 127.0.0.1:64185]
HTTP GET /events/player/players:5_6 301 [0.01, 127.0.0.1:64187]
HTTP POST /send_player_message/6 200 [0.07, 127.0.0.1:64190]
HTTP POST /send_player_message/5 200 [0.08, 127.0.0.1:64194]
Internal Server Error: /send_player_message/5
Traceback (most recent call last):
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/django/views/decorators/http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/not-workme/git-repositories/me/bridge/server/project/app/views/misc.py", line 29, in non_players_piss_off
    return view_function(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/not-workme/git-repositories/me/bridge/server/project/app/views/player.py", line 198, in send_player_message
    send_event(
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/django_eventstream/eventstream.py", line 56, in send_event
    e = storage.append_event(channel, event_type, data)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/django_eventstream/storage.py", line 180, in append_event
    db_event.save()
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/django_eventstream/models.py", line 52, in save
    super(Event, self).save(*args, **kwargs)
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/django/db/models/base.py", line 1160, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/django/db/models/base.py", line 1201, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/django/db/models/query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/debug_toolbar/panels/sql/tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/debug_toolbar/panels/sql/tracking.py", line 160, in _record
    return method(sql, params)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/not-workme/Library/Caches/pypoetry/virtualenvs/bridge-server-c0c-Nw8y-py3.12/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: database is locked
HTTP POST /send_player_message/5 500 [0.13, 127.0.0.1:64193]
HTTP POST /send_player_message/5 200 [0.07, 127.0.0.1:64194]
HTTP POST /send_player_message/5 200 [0.02, 127.0.0.1:64193]
